version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "snapshot2archive"
s3_prefix = "me.tarun.dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"